{% set version = "4.1.3" %}

package:
  name: jupyterlab_latex
  version: {{ version }}

source:
  - url: https://pypi.io/packages/source/j/jupyterlab_latex/jupyterlab_latex-{{ version }}.tar.gz
    sha256: 4b512a1ca244bc22944197307fd7fac371239e017305c115a66dcd3b10ca0e76
  - url: https://raw.githubusercontent.com/jupyterlab/jupyterlab-latex/v{{ version }}/LICENSE
    sha256: bf187e29dbaa606292cc72428603aed9829a1999ee8243019f6e1cdfa2ac6f5d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install -vv --install-option="--skip-npm" .

requirements:
  host:
    - jupyter-packaging >=0.10,<1
    - jupyterlab >=3,<4
    - pip
    - python >=3.6
  run:
    - jupyter_server >=1.6,<2
    - jupyterlab >=3,<4
    - python >=3.6

test:
  imports:
    - jupyterlab_latex
  commands:
    - pip check
    - jupyter labextension list
    - jupyter labextension list 1>labextensions 2>&1
    - cat labextensions | grep "@jupyterlab/latex.*v{{ version.replace(".", "\\.") }}.*OK"  # [unix]
    - jupyter serverextension list
    - jupyter serverextension list 1>serverextensions 2>&1
    - cat serverextensions | grep "jupyterlab_latex.*{{ version.replace(".", "\\.") }}.*OK"  # [unix]
    - jupyter server extension list
    - jupyter server extension list 1>server_extensions 2>&1
    - cat server_extensions | grep "jupyterlab_latex.*{{ version.replace(".", "\\.") }}.*OK"  # [unix]
  requires:
    - pip

about:
  home: https://github.com/jupyterlab/jupyterlab-latex
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: JupyterLab extension for live editing of LaTeX documents
  description: |
    An extension for JupyterLab which allows for live-editing of LaTeX
    documents.
  doc_url: https://github.com/jupyterlab/jupyterlab-latex/blob/master/docs/advanced.md
  dev_url: https://github.com/jupyterlab/jupyterlab-latex

extra:
  recipe-maintainers:
    - jan-janssen
    - bollwyvl
